environment:
  SHELL: C:\MinGW\msys\1.0\bin\sh
  FLAVOR: pharo.cog.spur
  matrix:
    - platform: x86
      ARCH: win32x86
      SRC_ARCH: i386
#    - platform: x64
#      ARCH: win64x64
#      SRC_ARCH: x86_64
matrix:
  fast_finish: false
clone_depth: 5
branches:
  only:
    - merge-with-osvm
    - merge-with-osvm-win32
init:
  - git config --system core.longpaths true
install:
  - git submodule update --init --recursive
build_script:
  - 'cd %APPVEYOR_BUILD_FOLDER% & %SHELL% "cd scripts && sh build-sources.sh -a i386"'
  - 'cd %APPVEYOR_BUILD_FOLDER% & %SHELL% "cd opensmalltalk-vm && sh .travis_build.sh"'
  - 'cd %APPVEYOR_BUILD_FOLDER% & %SHELL% "cd scripts && sh pack-vm.sh"'
#test_script:
#  - 'cd %APPVEYOR_BUILD_FOLDER% & %SHELL% -lc "cd ./scripts; exec 0</dev/null; exec ./run-tests.sh"'
on_failure:
  - 'cd %APPVEYOR_BUILD_FOLDER% & %SHELL% "if [ -e ./image/PharoDebug.log ]; then cat ./image/PharoDebug.log; fi"'
  - 'cd %APPVEYOR_BUILD_FOLDER% & %SHELL% "if [ -e ./image/stdout ]; then cat ./image/stdout; fi"'
  - 'cd %APPVEYOR_BUILD_FOLDER% & %SHELL% "if [ -e ./image/stderr ]; then cat ./image/stderr; fi"'
before_deploy:
  - 'cd %APPVEYOR_BUILD_FOLDER% & %SHELL% "sh scripts/deploy-before.sh"'
deploy_script:
  - 'cd %APPVEYOR_BUILD_FOLDER% & %SHELL% "sh scripts/deploy-appveyor.sh"'