environment:
  FLAVOR: pharo.cog.spur
  matrix:
    - platform: x86
      ARCH: win32x86
      SRC_ARCH: i386
#    - platform: x64
#      ARCH: win64x64
#      SRC_ARCH: x86_64
matrix:
  fast_finish: false
clone_depth: 5
branches:
  only:
    - merge-with-osvm
    - merge-with-osvm-win32
init:
  - git config --system core.longpaths true
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
install:
  - git submodule update --init --recursive
build_script:
  - bash -c "cd scripts; exec ./build-sources.sh -a i386"
  - bash -c "cd opensmalltalk-vm; exec ./.travis_build.sh"
  - bash -c "cd scripts; exec ./pack-vm.sh"'
#test_script:
#  - bash -c "cd scripts; exec 0</dev/null; exec ./run-tests.sh"
on_failure:
  - bash -c "if [ -e ./image/PharoDebug.log ]; then cat ./image/PharoDebug.log; fi"
  - bash -c "if [ -e ./image/stdout ]; then cat ./image/stdout; fi"
  - bash -c "if [ -e ./image/stderr ]; then cat ./image/stderr; fi"
before_deploy:
  - bash -c "exec ./scripts/deploy-before.sh
deploy_script:
  - bash -c "exec ./scripts/deploy-appveyor.sh"