language: c

addons:
  apt:
    packages:
      # this are requirements for building the vm
      - debhelper
      - devscripts
      - libasound2-dev
      - libssl-dev
      - libfreetype6-dev
      - libx11-dev
      - libxext-dev
      - gcc-multilib
      - uuid-dev

matrix:
  include:
    - os: osx
      env: ARCH="macos64x64" FLAVOR="pharo.cog.spur" SRC_ARCH="x86_64"
      before_script:
        - rm -Rf opensmalltalk-vm/spur64src/*
    - os: osx
      env: ARCH="macos32x86" FLAVOR="pharo.cog.spur" SRC_ARCH="i386"
      before_script: 
        - rm -Rf opensmalltalk-vm/spursrc/*

#install:
#  - ./.travis_install.sh
script:
  - (cd scripts && ./buildSources.sh -a $SRC_ARCH)
  - (cd opensmalltalk-vm && $CHROOT ./.travis_build.sh)
  
