language: c
addons:
  apt:
    packages:
      - debhelper
      - devscripts
      - libasound2-dev
      - libssl-dev
      - libfreetype6-dev
      - libx11-dev
      - libxext-dev
      - gcc-multilib
      - uuid-dev
# Pharo special dependencies:
      - libsdl2-dev
matrix:
  include:
    - os: osx
      env: ARCH="macos64x64" FLAVOR="pharo.cog.spur" SRC_ARCH="x86_64"
    - os: osx
      env: ARCH="macos32x86" FLAVOR="pharo.cog.spur" SRC_ARCH="i386"
      after_deploy: 
        - sh post-deploy.sh
#    - os: linux
#      env: ARCH="linux32x86" FLAVOR="pharo.cog.spur" SRC_ARCH="i386"
    - os: linux
      env: ARCH="linux32ARMv6" FLAVOR="pharo.cog.spur" SRC_ARCH="i386" CHROOT="schroot -p -c rpi
        -- bash -c "
      sudo: required
#      dist: trusty
#      group: edge
      install:
        - (cd opensmalltalk-vm && ./.travis_install.sh)
script:
  - (cd scripts && ./buildSources.sh -a $SRC_ARCH)
  - (cd opensmalltalk-vm && $CHROOT ./.travis_build.sh)
before_deploy: 
  - sh pre-deploy.sh
deploy:
  provider: bintray
  file: .bintray.json
  user: estebanlm
  key: $BINTRAY_API_KEY
  on: merge-with-osvm