language: c

addons:
  apt:
    packages:
      # this are requirements for building the vm
      - debhelper
      - devscripts
      - libasound2-dev
      - libssl-dev
      - libfreetype6-dev
      - libx11-dev
      - libxext-dev
      - gcc-multilib
      - uuid-dev

matrix:
  include:
    - os: osx
      env: ARCH="macos64x64" FLAVOR="pharo.cog.spur"
      before_script: bash -c "cd scripts && buildSources.sh -a i386"
    - os: osx
      env: ARCH="macos32x86" FLAVOR="pharo.cog.spur"
      before_script: bash -c "cd scripts && buildSources.sh -a x86_64"

#install:
#  - ./.travis_install.sh
script:
  - $CHROOT ./.travis_build.sh
